# Generated by Django 4.2.3 on 2023-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
