# Generated by Django 4.2.3 on 2023-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_product_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_available_stock',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
