# Generated by Django 4.2.3 on 2023-08-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('orders', '0003_remove_order_payment_method_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cart_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem'),
        ),
    ]
